version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3000
    networks:
      - api_marquei-network
    command: sh -c "pnpm install && pnpm dev"

networks:
  api_marquei-network:
    external: true 